#!/bin/bash

usage() {
    echo "usage: Watopoly">&2
    echo "-load filename">&2
    echo "-testing">&2
}

if [ $# -eq 0 ]; then
    ./Watopoly false "" false
elif [ $# -eq 2 ]; then
    if [ $1 == "-load" ]; then
        ./Watopoly true "$2" false
    elif [ $1 == "-testing" ]; then
        ./Watopoly false "" true
    fi
elif [ $# -eq 3 ]; then
    ./Watopoly true "$2" true
fi
